name: Bug report
description: Create a report to help us improve
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report for the **Drustcraft Engine**! Fill out the following form to your best ability to help us fix the problem.
      Only use this if you're absolutely sure that you found a bug and can reproduce it. For anything else, use: [our Discord server](https://drustcraft.com.au/discord), [the FAQ](https://github.com/Drustcraft/Drustcraft-Engine/wiki/FAQ) or the [Common Issues](https://github.com/Drustcraft/Drustcraft-Engine/wiki/Common-Issues).
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: To Reproduce
    description: Steps to reproduce this behaviour
    placeholder: |
      1. Go to '...'
      2. Click on '...'
      3. Scroll down to '...'
      4. See error
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected behaviour
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshots / Videos
    description: If applicable, add screenshots to help explain your problem.
- type: input
  attributes:
    label: Client Version and Platform
    description: |
      * Give us the exact version of your Minecraft client and if it is Java/Bedrock. Saying "latest" does not help us at all.
    placeholder: "For example: Bedrock 1.16.220"
- type: textarea
  attributes:
    label: Additional Context
    description: Add any other context about the problem here