# For more information, check out the plugin manual or join us on Discord:
# http://www.mythicmobs.net
#  
Configuration:
  Version: 4.9
  General:
    AllowMetrics: true
    CheckForUpdates: true
    CompatibilityMode: false
    DebugLevel: 0
    ErrorLogging: true
    Language: enUS
    UseVolatileFeatures: true
  Clock:
    ClockInterval: 5
    SaveInterval: 5
    SpawnsInterval: 2
    ScannerInterval: 10
    CleanupInterval: 600
  Components:
    CustomSpawners: true
    RandomSpawning: true
  Mobs:
    DespawnByDefault: true
    EnableAIModifiers: true
    EnableTimerSkills: true
    EnableThreatTables: true
    EnablePlayerFactions: true
    EnableLegacySkills: true
    KillMessagePrefix: ''
    PreventOtherDropsByDefault: false
    ShowHealth:
        Radius: 25
        Format: <mob.name> - <mob.php> (<mob.hp> / <mob.mhp>)
    Scaling:
      Default:
        Enabled: true
        PerBlocksFromSpawn: 250
    ScalingEquations:
      Health: V * ((1.05)^(L-1))
      Damage: V * ((1.05)^(L-1))
    DefaultLevelModifiers:
      Health: 0.1
      Armor: 0
      Damage: 0
      KnockbackResistance: 0
      Power: 0
  RandomSpawning:
    DisableVanillaSpawns: false
    GenerateSpawnPoints: true
    MaxMobsPerChunk: 80
    SpawnRadiusPerPlayer: 64
    SpawnRadiusPerPlayerY: 32
    DespawnLazyRandomMobs: true
    MaxGenerationTime: 20
    PointsPerSecond:
      Land: 10
      Air: 1
      Sea: 0
      Lava: 0
      Ground: 1
  Compatibility:
    Heroes:
      Enabled: false
    McMMO:
      Enabled: false
      ShowXPMessage: true
      XPMessageFormat: '&7You receive <drop.amount> experience for slaying <dropper.name>'
    SkillAPI:
      Enabled: false
      ShowXPMessage: true
      XPMessageFormat: '&7You receive <drop.amount> experience for slaying <dropper.name>'
    Vault:
      Enabled: false
      ShowMoneyMessage: true
      MoneyMessageFormat: '&7You receive <drop.amount> currency for slaying <dropper.name>'
